version: "3"
services:
  test:
    image: mysql:5
    tmpfs:
      - "/var/lib/mysql"

    ports:
      - "23306:3306"
    expose:
      - 23306
    environment:
      MYSQL_DATABASE: "bq_test"
      MYSQL_USER: "bq"
      MYSQL_PASSWORD: "test_secret"
      MYSQL_ROOT_PASSWORD: "test_secret"
    restart: always
    networks:
      - private
      - public
networks:
  public:
    internal: false
  private:
    internal: true
