DROP DATABASE IF EXISTS bq_test;

CREATE DATABASE bq_test;

USE bq_test;

-- USERS TABLE
CREATE TABLE users(
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(16) NOT NULL,
  password VARCHAR(60) NOT NULL,
  rolesAdmin TINYINT default 0 NOT NULL
);